# Generated by Django 4.1.2 on 2022-10-13 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='slug',
        ),
        migrations.AddField(
            model_name='conversation',
            name='name',
            field=models.CharField(default='', max_length=300, unique=True),
            preserve_default=False,
        ),
    ]
